image: elixir:latest

services:
  - postgres:latest

variables:
  MIX_ENV: "test"
  POSTGRES_DB: sibt_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"

stages:
  - style_format
  - coverage
  - test

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix ecto.setup

style_format:
  stage: style_format
  script:
    - mix format --check-formatted
    - mix credo --ignore refactor

coverage:
  stage: coverage
  script:
    - mix ecto.drop
    - mix ecto.create
    - mix coveralls

test:
  stage: test
  script:
    - mix ecto.drop
    - mix ecto.create
    - mix ecto.migrate
    - mix test

